# Generated by Django 4.2.2 on 2023-07-31 12:07

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=13, null=True, unique=True, validators=[app.validators.validate_phone_number]),
        ),
    ]
