# Generated by Django 4.2.3 on 2023-07-31 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_seller_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Seller', 'verbose_name_plural': 'Sellers'},
        ),
    ]
